services:
  container_dir:
    image: skorp321/football-streamlit
    build:
      context: .
      dockerfile: Dockerfile      
    volumes:
      - /home/adminai/Documents/Projects/panorama123:/container_dir
    command: /bin/sh -c "cd Deep-EIoU/Deep-EIoU && streamlit run tools/main.py"    
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

